import { NextRequest, NextResponse } from 'next/server';
import { getAuthContext, errorResponse } from '@/lib/api-helpers';

/**
 * POST /api/pageforge/designer-suggestions/send-email
 * Send an email to a designer with feedback from designer suggestions.
 */
export async function POST(request: NextRequest) {
  const auth = await getAuthContext();
  if (!auth.ok) return auth.response;

  const body = await request.json().catch(() => ({}));
  const { to, subject, body: emailBody, build_id } = body;

  if (!to?.trim()) return errorResponse('Recipient email is required');
  if (!subject?.trim()) return errorResponse('Subject is required');
  if (!emailBody?.trim()) return errorResponse('Email body is required');

  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) return errorResponse('Email service not configured', 500);

  const fromEmail = process.env.RESEND_FROM_EMAIL || 'noreply@dailycookie.co';

  // Convert plain text to simple HTML
  const htmlBody = emailBody
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;line-height:1.6;color:#1a1a2e;max-width:600px;">
      <div style="background:#1a1f36;border-radius:12px;padding:16px 20px;margin-bottom:20px;">
        <h1 style="color:#fff;font-size:16px;margin:0;">Kivi Media - PageForge</h1>
      </div>
      <p>${htmlBody}</p>
      <hr style="border:none;border-top:1px solid #eee;margin:24px 0;">
      <p style="color:#999;font-size:11px;">This feedback was generated by the KM PageForge build system.</p>
    </div>
  `.trim();

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${resendKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: fromEmail,
        to: [to.trim()],
        subject: subject.trim(),
        html,
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      return errorResponse(`Email failed: ${errText}`, 500);
    }

    const data = await res.json();

    // Log to build messages
    if (build_id) {
      const { supabase } = auth.ctx;
      try {
        await supabase
          .from('pageforge_build_messages')
          .insert({
            build_id,
            role: 'system',
            sender_name: 'System',
            content: `Designer feedback email sent to ${to.trim()}`,
            metadata: { email_id: data.id, recipient: to.trim() },
          });
      } catch {
        // non-critical
      }
    }

    return NextResponse.json({ success: true, email_id: data.id });
  } catch (err) {
    return errorResponse(
      err instanceof Error ? err.message : 'Failed to send email',
      500,
    );
  }
}
